created initial express server
Webwiznitr/Hacktoberfest-Tulip pull request #7
Opened 2023-10-25 06:05 UTC by avishkaindula

2023-10-25 12:56 UTC, AmreetKumarkhuntia approved these changes

2023-10-25 12:59 UTC, AmreetKumarkhuntia commented
@avishkaindula can you add a readme file for the installation procedure so that everyone can follow that installation guide to run the server on their local devices?

2023-10-25 13:01 UTC, AmreetKumarkhuntia commented on server/index.js
Can you move the index and routes file to another folder src?

2023-10-25 13:04 UTC, avishkaindula commented on server/index.js
Sure. Will do @AmreetKumarkhuntia

2023-10-25 13:38 UTC, avishkaindula commented
@AmreetKumarkhuntia I've created the installation guide on README.md and moved the index.js and routes folder into src directoroy.
Thank you.

2023-10-26 18:37 UTC, AmreetKumarkhuntia requested changes
Add the Readme file inside the server folder

2023-10-26 18:38 UTC, AmreetKumarkhuntia commented
#3

2023-10-26 18:40 UTC, AmreetKumarkhuntia commented
@avishkaindula please add a commit for the required changes.

2023-10-26 18:49 UTC, merged